# Configuration file for [MkDocs](https://mkdocs.org)
#
# This configuration requires the following pip packages to work:
# - mkdocs
#
# To build the documentation:
# > mkdocs build
#
# To serve the documentation locally:
# > mkdocs serve

site_name: pyspect
site_url: 'https://kth-sml.github.io/pyspect/'
site_author: 'Kaj Munhoz Arfvidsson <kajarf@kth.se>'
site_description:
  A method-agnostic toolbox that compiles temporal-logic specifications into
  reachability programs via Temporal Logic Trees (TLTs).

repo_url: https://github.com/KTH-SML/pyspect
copyright: "2025, Kaj Munhoz Arfvidsson"

theme: 
  name: shadcn
  icon: media/icon.svg

nav:
  - Home: index.md
  - Get Started: get_started.md
  - Core Concepts & Reference:
    - Set Builders: reference/set_builder.md
    - Logic Fragments: reference/logics.md
    - Temporal Logic Trees: reference/tlt.md
    - TLT Primitives: reference/primitives.md
  - Implementations:
    - hj_reachability: implementations/hj_reachability.md
    - zonoOpt: implementations/zonoOpt.md
  - Helper Implementations:
    - Base: implementations/base.md
    - Axes: implementations/axes.md
    - Plotly: implementations/plotly.md
    - Debug: implementations/debug.md

extra_javascript:
  - mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
          paths:
            - src/pyspect

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:
